# Changes here will be overwritten by Copier
_commit: v0.10.10
_src_path: https://github.com/fohte/generic-boilerplate
auto_merge_release_pr: true
binary_name: infractl
description: '@fohte''s personal CLI for infra operations'
is_public: true
project_name: infractl
release_binary: true
release_type: rust
repo_id: '1316143821'
repo_language: ja
subpackages: []
type: rust
use_coverage: true
use_release_please: true
